AppNetRazor/AppNetRazor/Pages/Cursos/Crear.cshtml.cs
using AppNetRazor.Datos;
using AppNetRazor.Modelos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace AppNetRazor.Pages.Cursos
{
    public class CrearModel : PageModel
    {
        private readonly ApplicationDbContext _contexto;

        public CrearModel(ApplicationDbContext contexto)
        {
            _contexto = contexto;
        }

        [BindProperty]
        public Curso Curso { get; set; }

        [TempData]
        public string Mensaje { get; set; }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Curso.FechaCreacion = DateTime.Now;

            _contexto.Add(Curso);

            await _contexto.SaveChangesAsync();
            Mensaje = "Curso Creado Correctamente";
            return RedirectToPage("Index");
        }
    }
}

AppNetRazor/AppNetRazor/Pages/Cursos/Editar.cshtml.cs
using AppNetRazor.Datos;
using AppNetRazor.Modelos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AppNetRazor.Pages.Cursos
{
    public class EditarModel : PageModel
    {
        private readonly ApplicationDbContext _contexto;

        public EditarModel(ApplicationDbContext contexto)
        {
            _contexto = contexto;
        }

        [BindProperty]
        public Curso Curso { get; set; }
        [TempData]
        public string Mensaje { get; set; }
        public async void OnGet(int id)
        {
            Curso = await _contexto.Curso.FindAsync(id);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var CursoDesdeDb = await _contexto.Curso.FindAsync(Curso.Id);

                CursoDesdeDb.NombreCurso = Curso.NombreCurso;
                CursoDesdeDb.CantidadClase = Curso.CantidadClase;
                CursoDesdeDb.Precio = Curso.Precio;


                await _contexto.SaveChangesAsync();
                Mensaje = "Curso Editado Correctamente";
                return RedirectToPage("Index");
            }

            return Page();
        }
    }
}

AppNetRazor/AppNetRazor/Pages/Cursos/Index.cshtml.cs
using AppNetRazor.Datos;
using AppNetRazor.Modelos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace AppNetRazor.Pages.Cursos
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _contexto;
        public IEnumerable<Curso> Cursos { get; set; }

        [TempData]
        public string Mensaje { get; set; }

        public IndexModel(ApplicationDbContext contexto)
        {
            _contexto = contexto;
        }
        public async Task OnGet()
        {
            Cursos = await _contexto.Curso.ToListAsync();
        }

        public async Task<IActionResult> OnPostBorrarAsync(int id)
        {
            var curso = await _contexto.Curso.FindAsync(id);

            if (curso is null) return NotFound();

            _contexto.Curso.Remove(curso);

            await _contexto.SaveChangesAsync();
            Mensaje = "Curso Eliminado Correctamente";
            return RedirectToPage("Index");
        }
    }
}

AppNetRazor/AppNetRazor/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace AppNetRazor.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AppNetRazor/AppNetRazor/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AppNetRazor.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

AppNetRazor/AppNetRazor/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AppNetRazor.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

AppNetRazor/AppNetRazor/Pages/Cursos/Crear.cshtml
@page
@model AppNetRazor.Pages.Cursos.CrearModel
@{
    ViewData["Title"] = "Crear nuevo Curso";
}

<h3 class="text-center">Visita mi Repositorio en<a href="https://github.com/juansubas" target="_blank"> GitHub </a></h3>

<div class="card">
    <div class="card-header">
        <h2 class="text-info">@ViewData["Title"]</h2>
    </div>
    <div class="card-body">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="container" style="padding:30px">
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Curso.NombreCurso"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Curso.NombreCurso" class="form-control" />
                        </div>
                        <span asp-validation-for="Curso.NombreCurso" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Curso.CantidadClase"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Curso.CantidadClase" class="form-control" />
                        </div>
                        <span asp-validation-for="Curso.CantidadClase" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Curso.Precio"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Curso.Precio" class="form-control" />
                        </div>
                        <span asp-validation-for="Curso.Precio" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2 offset-sm-2">
                            <input type="submit" value="Crear" class="btn btn-primary form-control"/>
                        </div>
                        <div class="col-sm-4">
                            <a asp-page="Index" class="btn btn-success form-control">Volver a la lista</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>  

AppNetRazor/AppNetRazor/Pages/Cursos/Editar.cshtml
@page
@model AppNetRazor.Pages.Cursos.EditarModel
@{
    ViewData["Title"] = "Editar Curso";
}

<h3 class="text-center">Visita mi Repositorio en<a href="https://github.com/juansubas" target="_blank"> GitHub </a></h3>

<div class="card">
    <div class="card-header">
        <h2 class="text-info">@ViewData["Title"]</h2>
    </div>
    <div class="card-body">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <!-- Se envia campo oculto -->

            <input type="hidden" asp-for="Curso.Id" />

            <div class="container" style="padding:30px">
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Curso.NombreCurso"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Curso.NombreCurso" class="form-control" />
                        </div>
                        <span asp-validation-for="Curso.NombreCurso" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Curso.CantidadClase"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Curso.CantidadClase" class="form-control" />
                        </div>
                        <span asp-validation-for="Curso.CantidadClase" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Curso.Precio"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Curso.Precio" class="form-control" />
                        </div>
                        <span asp-validation-for="Curso.Precio" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2 offset-sm-2">
                            <input type="submit" value="Editar" class="btn btn-primary form-control" />
                        </div>
                        <div class="col-sm-4">
                            <a asp-page="Index" class="btn btn-success form-control">Volver a la lista</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>  

AppNetRazor/AppNetRazor/Pages/Cursos/Index.cshtml
@page
@model AppNetRazor.Pages.Cursos.IndexModel
@{
    ViewData["Title"] = "Lista de cursos";
}

<h3 class="text-center">Visita mi Repositorio en<a href="https://github.com/juansubas" target="_blank"> GitHub </a></h3>

@if (Model.Mensaje is not null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @Model.Mensaje
        <button type="button" class="btn-close" data-bs-dismiss="alert" arial-label="Close"></button>
    </div>
}
<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-sm-6">
                <h2 class="text-info">Lista de Cursos</h2>
            </div>
            <div class="col-sm-6">
                <a asp-page="Crear" class="btn btn-primary">Crear Nuevo Curso</a>
            </div>
        </div>
        <div class="card-body">
            <form method="post">
                @if (Model.Cursos.Count() > 0)
                {
                    <br /><br />
                    <table class="table table-stripped border">
                        <tr class="table-secondary">
                            <th>@Html.DisplayNameFor(m => m.Cursos.First().Id)</th>
                            <th>@Html.DisplayNameFor(m => m.Cursos.First().NombreCurso)</th>
                            <th>@Html.DisplayNameFor(m => m.Cursos.First().CantidadClase)</th>
                            <th>@Html.DisplayNameFor(m => m.Cursos.First().Precio)</th>
                            <th>@Html.DisplayNameFor(m => m.Cursos.First().FechaCreacion)</th>
                            <th>Acciones</th>
                        </tr>
                        @foreach (var item in Model.Cursos)
                        {
                            <td>@Html.DisplayFor(m => item.Id)</td>
                            <td>@Html.DisplayFor(m => item.NombreCurso)</td>
                            <td>@Html.DisplayFor(m => item.CantidadClase)</td>
                            <td>@Html.DisplayFor(m => item.Precio)</td>
                            <td>@Html.DisplayFor(m => item.FechaCreacion)</td>
                            <td>
                                <a asp-route-id="@item.Id" asp-page="Editar" class="btm btn-sm btn-success">
                                    Editar
                                </a>
                                <button asp-page-handler="Borrar" asp-route-id="@item.Id"
                                onclick="return confirm('Esta seguro de eliminar este curso?')"
                                class="btn btn-sm btn-danger">Borrar</button>
                            </td>
                        }
                        <tr>
                            <td></td>
                        </tr>
                    </table>
                }else
                {
                    <p>No hay cursos disponibles</p>
                }
            </form>
        </div>
    </div>
</div>  

AppNetRazor/AppNetRazor/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <h3 class="text-center">Visita mi Repositorio en <a href="https://github.com/juansubas" target="_blank" >GitHub</a></h3>
</div>

AppNetRazor/AppNetRazor/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppNetRazor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppNetRazor.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">AppNetRazor</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Cursos/Index">Cursos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AppNetRazor - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>